### ISSUE TITLE
set-files not working

### ISSUE THREAD

**Issue by seehat** [jenstornell/kirby-bricks#1]
Thx for this plugin, I am currently trying and getting used to it. :)

I try to include several files with the files directories for global files and this isn't working now. 

When i create the folder:

`site/templates/global/snippets/pageheader.php`

`set-files` tries to find the following file, which is wrong:

`site/templates/global/snippets/pageheader.php/pageheader.php`

Does this work for you, or have I used it wrong?

**Comment by jenstornell** [comment]
Right now it's working more like Kirby Patterns plugin which means that it's more modular, like this:

```text
snippets/my-snippet/style.scss
snippets/my-snippet/script.js
snippets/my-snippet/my-snippet.php

snippets/another-snippet/style.scss
snippets/another-snippet/another-snippet.php
```

I have a new improved way of handling snippets on my localhost that is not released yet.

So I think it's woking as expected but lacks of a fallback to the old way of using snippets.

**Comment by seehat** [comment]
Ok, I see. thx for your fast reply.
